apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskmanager.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
